CREATE DATABASE artistmgmt;

CREATE TABLE artist( id SERIAL PRIMARY KEY, name VARCHAR (256) NOT NULL, dob TIMESTAMP, gender VARCHAR(1) CHECK (gender IN('m', 'f', 'o')), first_release_year INT, no_of_album_released INT, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE "user"( id SERIAL PRIMARY KEY, first_name VARCHAR(256) NOT NULL, last_name VARCHAR(256) NOT NULL, email VARCHAR(256) UNIQUE NOT NULL, password VARCHAR(256) UNIQUE NOT NULL, phone VARCHAR(20) NOT NULL, gender VARCHAR(1) CHECK (gender IN('m', 'f', 'o')), address VARCHAR(256) NOT NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE music( artist_id INT, title VARCHAR(256) NOT NULL, album_name VARCHAR(256), genre VARCHAR(256) CHECK (genre IN('rnb', 'country', 'classic', 'rock', 'jazz')), createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (artist_id) REFERENCES artist(id) );